
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "./"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: "gradle"
    directory: "./android"
    schedule:
      interval: "weekly"
    target-branch: "dev"
