name: inteligencias_multiplas
description: Complete todas as etapas escolhendo sua afinidade com cada pergunta, Com o método intuitivo escolhendo suas preferencias com a pergunta de acordo com o emoji , sendo disponível usar os emojis inferiores para transitar entres as perguntas, se divirta respondendo e ganhando seu resultado , chance unica de descobrir mais sobre você

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.7.2+47

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  firebase_core: ^2.25.4
  firebase_auth: ^4.20.0
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  google_sign_in: ^6.1.3
  flutter_facebook_auth: ^6.2.0
  url_launcher: ^6.2.6
  firebase_database: ^10.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/logo.png
    - assets/icons/logoFull.png
    - assets/icons/brain_login.png
    - assets/icons/google_icon.png
    - assets/icons/facebook_icon.png
    - assets/icons/play.png
    - assets/icons/star.png
    - assets/icons/starFull.png
    - assets/icons/desenvolvedores.png
    - assets/icons/sobreApp.png
    - assets/icons/termosUso.png
    - assets/icons/sair.png
    - assets/icons/refazer.png
    - assets/icons/proximo.png
    - assets/icons/edit.png
    - assets/icons/arrowdetailresult.png
    - assets/etapas/etapa-1/pergunta-1.png
    - assets/resultado/concluido.png
    - assets/resultado/cinestesica.png
    - assets/resultado/espacial.png
    - assets/resultado/interpessoal.png
    - assets/resultado/intrapessoal.png
    - assets/resultado/linguistico.png
    - assets/resultado/logico.png
    - assets/resultado/musical.png
    - assets/icons/github.png
    - assets/icons/linkedin.png
    - assets/icons/instagram.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
